### PR TITLE
Add 802.11ax(wifi6) ability

### PR DESCRIPTION
**Pull request by Catty2014**
This PR adds 802.11ax(wifi6) ability to create_ap and GUI.
This PR solves #357 
In create_ap, an option named `--ieee80211ax` is added.
In GUI, a checkbox "IEEE80211ax" is added.

### CODE REVIEW

**Comment by lakinduakash** [comment]
Thanks for the contribution. Were you able to compile this with the current Makefile? What is the gtk version you used?

**Comment by Catty2014** [comment]
I use gtk 3.24.38 and it compiles successfully.

2023年11月24日 05:05:58 Lakindu Akash ***@***.***>:

**Comment by unphased** [comment]
This would be epic. So far I am able to get AC 40mhz working on my `Intel Corporation Wi-Fi 6 AX200 (rev 1a)`, can only get a 40Mhz band by leaving Channel as Auto because none of the higher than 20mhz channels i tried would actually work. But somehow the default channel 36 can sometimes connect as AC on 40Mhz leading to 300 or so Mbit which is okay, but not stellar. Being able to obtain AX would be wonderful...

**Comment by unphased** [comment]
Update: Not working for me on this particular hardware of mine. It just produces the usual "Failed to run hostapd" error

**Comment by robertkirkman** [comment]
WORKING for me. 
- radio: MEDIATEK Corp. MT7921K (RZ608) Wi-Fi 6E 80MHz
- driver: `mt7921e`
- `FREQ_BAND=5`
- `IEEE80211AX=1`
- init system executes `iw reg set US` **before** `create_ap`. This both vastly improves my bandwidth and fixes "`ERROR: Your adapter can not transmit to channel 36, frequency band 5GHz.`"
- speedtest.net result now BETTER with my Wi-Fi 6 connected device (320 Mbps) than with a Wi-Fi 5 connected device (70 Mbps). Ethernet WAN on the AP device gets 350 Mbps.

Thank you!!!

**Comment by copitz** [comment]
Works fine for me - thank you very much! (IMHO this could and should be merged)

**Comment by lakinduakash** [comment]
ATM I don't have an Ubuntu machine, But I hope it compiles and works fine as others feedback. Thanks for the contribution

**Comment by TriMoon** [comment]
@unphased 
> Update: Not working for me on this particular hardware of mine. It just produces the usual "Failed to run hostapd" error

That is caused by the intel driver limiting functionality, it's same on `AX210`...
Intel's LAR _(Locality Aware Regulator)_ is what is screwing us over...

**Comment by lilkidsuave** [comment]
Can you make it also compatible with 6e?

**Pull request merged**
