### PR TITLE
feat(.desktop): include script to create system shortcut

### PR DESCRIPTION
**Pull request by fabricio-godoi**
As mentioned in #10 I create a .desktop that is able to run the application.
I'm not a artist, so I download the icon from a opensource website and put the disclaimer to it.

Tested the install/uninstall procedure in Manjaro KDE and PopOS Gnome.

### CODE REVIEW

**Comment by lakinduakash** [comment]
Hi, nice work.
Let me add few suggestions.
- Can you create a folder called `src/desktop` and move `.desktop` file and icon to that folder
- Then move  `install` and `uninstall` instructions you added to [CMakeLists.txt](https://github.com/lakinduakash/linux-wifi-hotspot/blob/master/src/CMakeLists.txtl) under `install_build` and `uninstall_build`. 

Ex:
```Makefile
COMMAND install -Dm644 ${CMAKE_SOURCE_DIR}/desktop/hotspot.png $ENV{DESTDIR}/share/doc/create_ap/hotspot.png

COMMAND install -Dm644 ${CMAKE_SOURCE_DIR}/desktop/wifihotspot.desktop $ENV{DESTDIR}/share/applications/wifihotspot.desktop
```

**Comment by fabricio-godoi** [comment]
I added the sugestion changes to the project. I hope this got better now :smile:

**Comment by lakinduakash** [comment]
Great. Thanks. :)

**Comment by lakinduakash** [comment]
closes #10

**Pull request merged**
