### PR TITLE
Create debian package for project

### LINKED ISSUE #67: Create debian package
Add script to create deb package using the makfile

### PR DESCRIPTION
**Pull request by snhardin**
Still drafting this PR... build is working but need to do a little testing before calling this good.

Changes required to code:
* `systemd` service should not be installed to `/usr/lib`.

Closes #67

### CODE REVIEW

**Review by lakinduakash — APPROVED** [review]

**Comment by lakinduakash** [comment]
Good work! Inform when it is ready to merge

**Comment by snhardin** [comment]
Hi @lakinduakash. Sorry, I didn't actually follow some of the instructions given on the issue you opened. I didn't make this part of the makefile because the makefile would basically be calling `debuild` which would in turn call the makefile again. Plus, in Docker, it's much easier to grab all of the required dependencies in an isolated environment.

Are you okay with the changes made to the systemd service paths? `/lib/systemd` is the "proper" spot to place a systemd service according to Debian's package builder. Is there a reason why you were  using `/usr/lib/systemd`?

Other than these two things, this PR is ready to merge. Package seems to be working on my test environment.

**Comment by lakinduakash** [comment]
Hi,
Thank you for the contribution. Regarding your comment - 

> Are you okay with the changes made to the systemd service paths? /lib/systemd is the "proper" spot to place a systemd service 
> according to Debian's package builder. Is there a reason why you were using /usr/lib/systemd?

In ubuntu `/lib/systemd` is symlinked to `/usr/lib/systemd` . I don't know about the recomrndation of debian package builder. If it says like that this change is fine

>  in Docker, it's much easier to grab all of the required dependencies in an isolated environment.

Making it in docker is much better.

> I didn't make this part of the makefile because the makefile would basically be calling debuild which would in turn call the makefile again.

However I don't understand this line. Can you describe more aboute this.

**Comment by snhardin** [comment]
> However I don't understand this line. Can you describe more aboute this.

Sorry, I sent that message early in the morning my time. 🙂

Your original issue mentioned that you wanted a shortcut in your `Makefile` to be able to build the Debian package using `make`. I just wanted to know if you still want this even though the package is built via Docker.

**Comment by lakinduakash** [comment]
I tested everything and that's fine. Thank you for your contribution.

**Pull request merged**
